require: rubocop-performance
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Rails:
  Enabled: true

Layout/IndentFirstHashElement:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Metrics/ModuleLength:
  Exclude:
    - app/models/concerns/currencies.rb

Metrics/LineLength:
  Max: 200

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
