language: ruby
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
rvm:
  - 2.6
services:
  - postgresql

before_script:
  - psql -c 'create database airport_test;' -U postgres

script:
  - bundle exec rubocop
  - bundle exec rspec
