version: 2.1
orbs:
  ruby: circleci/ruby@0.2.1

jobs:
  build:
    executor: ruby/2.6.3
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - ruby/load-cache
      - ruby/run-tests
      - ruby/save-cache
