version: 2.1
orbs:
  ruby: circleci/ruby@0.2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - ruby/load-cache
      - ruby/run-tests
      - ruby/save-cache
