version: 2.1
orbs:
  ruby: circleci/ruby@0.2.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/load-cache
      - ruby/install-deps
      - ruby/save-cache
      - ruby/run-tests
